In [1]:
import numpy as np
print("checkerbord pattern")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkerbord pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
a=np.array([1,2,3,4,5])
print("first array")
print(a)
b=np.array([1,3,5])
print("second array")
print(b)
print(np.in1d(a,b))

first array
[1 2 3 4 5]
second array
[1 3 5]
[ True False  True False  True]


In [9]:
a=np.array([1,2,3,4,5])
print("first array")
print(a)
b=np.array([1,3,5,9])
print("second array")
print(b)
print("intersection")
print(np.intersect1d(a,b))
print("union")
print(np.union1d(a,b))

first array
[1 2 3 4 5]
second array
[1 3 5 9]
intersection
[1 3 5]
union
[1 2 3 4 5 9]


In [7]:
r=np.array([1,1,3,4,5,6,7])
print(np.unique(r))

[1 3 4 5 6 7]


In [11]:
s=np.array([9,8,6,5,3,1])
print("array:",s)
print("type:",type(s))
l=s.tolist()
print("list:",l)
print(type(l))

array: [9 8 6 5 3 1]
type: <class 'numpy.ndarray'>
list: [9, 8, 6, 5, 3, 1]
<class 'list'>


In [16]:
n=int(input("enter no.of element"))
l=[]
for i in range(n):
    l.append(input())
k=input("enter the number want to be remove")
while(l.count(k)>0):
    l.remove(k)
print(l)


enter no.of element5
hello
hi
ok
ok
hi
enter the number want to be removeok
['hello', 'hi', 'hi']


In [14]:
print("checkerbord pattern")
x=np.zeros((8,8),dtype=int)
x[::2,4::]=1
x[1::2,:4:]=1
print(x)

checkerbord pattern
[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


In [28]:
print("checkerbord pattern")
x=np.zeros((8,8),dtype=int)
x[0,:2:]=1
x[0,4:6:]=1
x[1::6,2:4:]=1
x[1::6,6::]=1
x[3:6:2,2:4:]=1
x[3:6:2,4:6:]=1
x[2:7:2,:2:]=1
x[2:7:2,6::]=1
print(x)

checkerbord pattern
[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 0 0 1 1]]
