In [1]:
#P13
import numpy as np
m=np.array([[1,2,8],[4,5,5],[9,2,5]])
print("Array:")
print(m)
print("first column:",m[:,0])
print("second column:",m[:,1])
print("thrid column:",m[:,2])

Array:
[[1 2 8]
 [4 5 5]
 [9 2 5]]
first column: [1 4 9]
second column: [2 5 2]
thrid column: [8 5 5]


In [4]:
#p14
m1=np.arange(9).reshape(3,3)
m2=np.ones((3,3),dtype=int)
print("first matrix")
print(m1)
print("second matrix")
print(m2)
r1=np.matmul(m1,m2)
print("Matrix multiplication")
print(r1)
r2=m1+m2
print("Sum of Matrix")
print(r2)

first matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
second matrix
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Matrix multiplication
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
Sum of Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#15
m=np.array([[1,0],[0,1]])
w,v=np.linalg.eig(m)
print("eigen values:",w)
print("eigen vector:",v)

eigen values: [1. 1.]
eigen vector: [[1. 0.]
 [0. 1.]]


In [10]:
#16
print("Matrix:")
print(m)
#m2=np.ones((3,3),dtype=int)
print("inverse")
x=np.linalg.inv(m)
print(x)

Matrix:
[[1 0]
 [0 1]]
inverse
[[1. 0.]
 [0. 1.]]


In [1]:
import numpy as np  
a = np.arange(1, 10)
np.savetxt('file.txt', a, delimiter=',')

In [2]:
import numpy as np      
data = np.array( [[10,20,30], [40,50,60], [70,80,90]] )
np.savetxt("test.csv", data, delimiter=",")

In [9]:
#For reading txt/csv file
import numpy as np 
np.loadtxt(open("test.csv","rb"),delimiter=",",dtype=np.int32)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)